model:
  name: IMDB
  initializer_name: random_uniform
  initializer_args:
    minval: -0.03
    maxval: 0.03
  input_dtype: int32
  target_dtype: int32
  vocab_size: 10000
  target_size: 2
  use_last_output: True
  embedding_size: 100
  cell_type: GRU
  cells:
    - num_units: 50
    - num_units: 50
  loss_func: sentence_loss
  dataset: imdb-small
train:
  epoch_num: 20
  num_steps: 100
  batch_size: 32
  keep_prob: 1.0
  optimizer: Adam 
  learning_rate: 0.0001
