model:
  name: YELP-GRU-200-1
  initializer_name: random_uniform
  initializer_args:
    minval: -0.1
    maxval: 0.1
  input_dtype: int32
  target_dtype: int32
  vocab_size: 10001
  target_size: 5
  use_last_output: True
  embedding_size: 200
  cell_type: GRU
  cells:
    - num_units: 200
      forget_bias: 1.0
  loss_func: sentence_loss
  dataset: yelp-small
train:
  epoch_num: 25
  num_steps: 250
  batch_size: 32
  keep_prob: 0.5
  gradient_clip: global_norm
  gradient_clip_args:
    clip_norm: 1.0
  optimizer: Adam
  learning_rate: 0.001

